name: 'GH actions stale run canceller'
author: 'Dmitry Rozhdestvenskiy <yellowmegaman@gmail.com>'
description: 'Shoots old builds'
branding:
  icon: 'target'
  color: 'yellow'
inputs:
  github_token:
    description: "our github token. we can refer by doing 'secrets.GITHUB_TOKEN'"
    required: true
  workflows_filter:
    description: "what workflows we'd like to stop"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{inputs.github_token}}
