name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_canceller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shot
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflows_filter: "CI|pr|build_canceller"
